; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
build_flags = 
    -D USB_MIDI_SERIAL
    -I ../../src
    -I ../../lib/Fonts
lib_deps = 
    ; Add your external library dependencies here
    MIDI
    file://../../ ; location of SSD1322 library
lib_extra_dirs = 
    ../../lib/Fonts

; Serial Monitor settings
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem154944801
monitor_filters = direct